### PR TITLE
A few bug fixes and enhancements

### PR DESCRIPTION
**Pull request by GReagle**
What do you think?

### CODE REVIEW

**Comment by GReagle** [comment]
On Sun, Dec 27, 2015 at 12:25:38PM -0800, Jan Klemkow wrote:

> > ```
> >  * roster list in Lua
> > ```
> > 
> > This roster implementation is a good idea, but I don't want to extend
> > the requirements with lua.  Maybe we could start a new repository for
> > this kind of extensions.

Okay.  Sorry about that.  That was mostly experimental.  I could put it
into my sj tools repository.

> > ```
> >  * sj can print all XML messages with -D option
> > ```
> > 
> > This feature should be implemented in a single place.  First, we have to
> > restructure the code, that all input and output flows over one or two
> > functions.  And there we have to place an if (debug == true)...

I am not very interested in rewriting sj as you describe above.  Not saying
that I would never do it, but it is not near the top of my list of what I
am interested in working on.  My -D feature is fine for me the way it is--I
think that it works well and is bug free.  What you describe does sound
better though.  Although "debug==true" is redundant, you could just do "if
(debug)".

> > ```
> >  * needs a license
> > ```
> > 
> > could you use the same licence text as inside of the source code files.
> > I prefer the default OpenBSD licence from
> > /usr/share/misc/license.template

I am very mistaken here.  There are already copyright notices in the source
files, which I overlooked.  I just assumed that it was being done in the
suckless style which is to have the copyright notice in the LICENSE file
and not in the source files.  So, now, I don't see any need for a license
file.

Do you want me to email you the patches individually, or do a pull request
or what?  Sorry for my ignorance, I am new to github.  My experience with
git so far has just been the suckless mailing list protocol of emailing
patches made by git format-patch.

**Comment by younix** [comment]
On Sun, Dec 27, 2015 at 02:59:12PM -0800, GReagle wrote:

> On Sun, Dec 27, 2015 at 12:25:38PM -0800, Jan Klemkow wrote:
> 
> > > - roster list in Lua
> > >   This roster implementation is a good idea, but I don't want to extend
> > >   the requirements with lua. Maybe we could start a new repository for
> > >   this kind of extensions.
> 
> Okay. Sorry about that. That was mostly experimental. I could put it
> into my sj tools repository.

a new repository "sj tools" sounds good.  There we could collect all
that clue code stuff and experimental programs in other languages.

> > > - sj can print all XML messages with -D option
> > >   This feature should be implemented in a single place. First, we have to
> > >   restructure the code, that all input and output flows over one or two
> > >   functions. And there we have to place an if (debug == true)...
> 
> I am not very interested in rewriting sj as you describe above. Not saying
> that I would never do it, but it is not near the top of my list of what I
> am interested in working on. My -D feature is fine for me the way it is--I
> think that it works well and is bug free. What you describe does sound
> better though. Although "debug==true" is redundant, you could just do "if
> (debug)".

I don't want you to do this.  I'll do it these days.

> > > - needs a license
> > >   could you use the same licence text as inside of the source code files.
> > >   I prefer the default OpenBSD licence from
> > >   /usr/share/misc/license.template
> 
> I am very mistaken here. There are already copyright notices in the source
> files, which I overlooked. I just assumed that it was being done in the
> suckless style which is to have the copyright notice in the LICENSE file
> and not in the source files. So, now, I don't see any need for a license
> file.

An extra LICENSE file it not that bad.  It is very common to have one,
that new people easily find this kind of information.

> Do you want me to email you the patches individually, or do a pull request
> or what? Sorry for my ignorance, I am new to github. My experience with
> git so far has just been the suckless mailing list protocol of emailing
> patches made by git format-patch.

I think one pull request per feature change is the right thing.

**Comment by younix** [comment]
single pull requests are better to merge and to discuss :-)

**Pull request closed without merging**
